name: run hello-world from py script
on: push

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v4

    - name: Setup python
      uses: uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: run a py script
      run: python hello.py
